// Curated session contract subpath. Keep root imports focused on BrewvaRuntime.
export {
  SESSION_REDO_SCHEMA,
  SESSION_REWIND_CHECKPOINT_SCHEMA,
  SESSION_REWIND_DIVERGENCE_SCHEMA,
  SESSION_REWIND_SCHEMA,
  SESSION_SUPERSEDE_SCHEMA,
} from "./domain/sessions/types.js";
export type {
  CreateBrewvaSessionOptions,
  ManagedToolMode,
  OpenToolCallRecord,
  OpenTurnRecord,
  RecordSessionRewindCheckpointInput,
  SessionHydrationState,
  SessionPromptSnapshot,
  SessionRedoFailureReason,
  SessionRedoInput,
  SessionRedoRecord,
  SessionRedoResult,
  SessionRewindCheckpointRecord,
  SessionRewindCheckpointStatus,
  SessionRewindDivergenceNote,
  SessionRewindFailureReason,
  SessionRewindInput,
  SessionRewindMode,
  SessionRewindRecord,
  SessionRewindResult,
  SessionRewindState,
  SessionRewindSummary,
  SessionRewindTargetLineage,
  SessionRewindTargetView,
  SessionRewindTrigger,
  SessionUncleanShutdownDiagnostic,
  SessionUncleanShutdownReason,
} from "./domain/sessions/types.js";
export type {
  AdoptSessionLineageOutcomeInput,
  CapabilityStateRecordedPayload,
  CapabilityStateRecord,
  ContextAdmission,
  ContextEntryPresentTo,
  ContextEntryRecordedPayload,
  ContextEntryRecord,
  CreateSessionLineageNodeInput,
  ForkPoint,
  GetContextEntryPathInput,
  LineageOutcomeAdmission,
  RecordCapabilityStateInput,
  RecordContextEntryInput,
  RecordSessionLineageOutcomeInput,
  RecordSessionLineageSelectionInput,
  RecordSessionLineageSummaryInput,
  SessionLineageEdge,
  SessionLineageNodeCreatedPayload,
  SessionLineageNodeKind,
  SessionLineageNodeRecord,
  SessionLineageNodeView,
  SessionLineageOutcomeAdoptedPayload,
  SessionLineageOutcomeAdoptionRecord,
  SessionLineageOutcomeRecord,
  SessionLineageOutcomeRecordedPayload,
  SessionLineageSelectionRecord,
  SessionLineageSelectionRecordedPayload,
  SessionLineageState,
  SessionLineageSummaryRecord,
  SessionLineageSummaryRecordedPayload,
  SessionLineageTree,
} from "./domain/sessions/lineage.js";
export {
  CAPABILITY_STATE_INLINE_DATA_MAX_BYTES,
  deriveSessionLineageState,
  findSessionLineageRoot,
  isLlmVisibleContextEntry,
} from "./domain/sessions/lineage.js";
export type {
  SessionLifecycleApprovalSnapshot,
  SessionLifecycleExecutionSnapshot,
  SessionLifecycleRecoverySnapshot,
  SessionLifecycleSnapshot,
  SessionLifecycleSnapshotBuildInput,
  SessionLifecycleSummaryKind,
  SessionLifecycleSummarySnapshot,
  SessionLifecycleToolingSnapshot,
  SessionLifecycleTransitionSnapshot,
} from "./domain/sessions/lifecycle.js";
export { SESSION_WIRE_SCHEMA } from "./domain/sessions/wire.js";
export type {
  ContextStatusView,
  SessionWireAttemptReason,
  SessionWireCommittedStatus,
  SessionWireDurability,
  SessionWireFrame,
  SessionWireFrameBase,
  SessionWireSource,
  SessionWireStatusState,
  SessionWireTransitionFamily,
  SessionWireTransitionStatus,
  SessionWireTurnTrigger,
  ToolOutputDisplayView,
  ToolOutputView,
  TurnInputRecordedPayload,
  TurnRenderCommittedPayload,
} from "./domain/sessions/wire.js";
export type {
  IntegrityDomain,
  IntegrityIssue,
  IntegritySeverity,
  IntegrityStatus,
} from "./domain/sessions/integrity.js";
export {
  TurnLifecycleSpine,
  compareTurnLifecycleGates,
  getTurnLifecycleFoldPlacements,
  getTurnLifecycleRecoveryPlacement,
  getTurnLifecycleRecoveryPlacements,
  type TurnLifecycleAdvanceInput,
  type TurnLifecycleGate,
  type TurnLifecycleRecoveryReason,
  type TurnLifecycleSnapshot,
} from "./domain/lifecycle/turn-lifecycle-spine.js";
export {
  buildSessionRewindProjection,
  listSessionRewindTargets,
} from "./domain/projection/session-rewind.js";
