import {
  DELEGATION_EVENT_DESCRIPTORS,
  SUBAGENT_CANCELLED_EVENT_DESCRIPTOR,
  SUBAGENT_COMPLETED_EVENT_DESCRIPTOR,
  SUBAGENT_DELIVERY_SURFACED_EVENT_DESCRIPTOR,
  SUBAGENT_FAILED_EVENT_DESCRIPTOR,
  SUBAGENT_OUTCOME_PARSE_FAILED_EVENT_DESCRIPTOR,
  SUBAGENT_RUNNING_EVENT_DESCRIPTOR,
  SUBAGENT_SPAWNED_EVENT_DESCRIPTOR,
  WORKER_RESULTS_APPLIED_EVENT_DESCRIPTOR,
  readDelegationLifecycleEventPayload,
  readWorkerResultsAppliedEventPayload,
} from "../domain/delegation/event-descriptors.js";
import {
  DECISION_RECEIPT_RECORDED_EVENT_DESCRIPTOR,
  EFFECT_COMMITMENT_APPROVAL_CONSUMED_EVENT_DESCRIPTOR,
  EFFECT_COMMITMENT_APPROVAL_DECIDED_EVENT_DESCRIPTOR,
  EFFECT_COMMITMENT_APPROVAL_REQUESTED_EVENT_DESCRIPTOR,
  PROPOSALS_EVENT_DESCRIPTORS,
  readEffectCommitmentApprovalRequestedEventPayload,
  readEffectCommitmentApprovalResolutionEventPayload,
  readEffectCommitmentDecisionReceiptRecordedEventPayload,
} from "../domain/proposals/event-descriptors.js";
import {
  REASONING_EVENT_DESCRIPTORS,
  REASONING_REVERT_EVENT_DESCRIPTOR,
  readReasoningRevertEventPayload,
} from "../domain/reasoning/event-descriptors.js";
import {
  SESSIONS_EVENT_DESCRIPTORS,
  SESSION_REWIND_COMPLETED_EVENT_DESCRIPTOR,
  SESSION_TITLE_RECORDED_EVENT_DESCRIPTOR,
  SESSION_TURN_TRANSITION_EVENT_DESCRIPTOR,
  SESSION_UNCLEAN_SHUTDOWN_RECONCILED_EVENT_DESCRIPTOR,
  TURN_INPUT_RECORDED_EVENT_DESCRIPTOR,
  TURN_RENDER_COMMITTED_EVENT_DESCRIPTOR,
  readSessionRewindCompletedEventPayload,
  readSessionTitleRecordedEventPayload,
  readSessionTurnTransitionEventPayload,
  readSessionUncleanShutdownDiagnosticEventPayload,
  readTurnInputRecordedEventPayload,
  readTurnRenderCommittedEventPayload,
} from "../domain/sessions/event-descriptors.js";
import {
  CAPABILITY_STATE_RECORDED_EVENT_DESCRIPTOR,
  CONTEXT_ENTRY_RECORDED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_EVENT_DESCRIPTORS,
  SESSION_LINEAGE_NODE_CREATED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_OUTCOME_ADOPTED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_OUTCOME_RECORDED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_SELECTION_RECORDED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_SUMMARY_RECORDED_EVENT_DESCRIPTOR,
  readCapabilityStateRecordedEventPayload,
  readContextEntryRecordedEventPayload,
  readSessionLineageNodeCreatedEventPayload,
  readSessionLineageOutcomeAdoptedEventPayload,
  readSessionLineageOutcomeRecordedEventPayload,
  readSessionLineageSelectionRecordedEventPayload,
  readSessionLineageSummaryRecordedEventPayload,
} from "../domain/sessions/lineage-event-descriptors.js";
import { SKILLS_EVENT_DESCRIPTORS } from "../domain/skills/event-descriptors.js";
import {
  TASK_EVENT_DESCRIPTORS,
  TASK_STALL_ADJUDICATED_EVENT_DESCRIPTOR,
  TASK_STUCK_DETECTED_EVENT_DESCRIPTOR,
  readTaskStallAdjudicatedEventPayload,
  readTaskStuckDetectedEventPayload,
} from "../domain/task/event-descriptors.js";
import {
  TOOLS_EVENT_DESCRIPTORS,
  TOOL_CALL_BLOCKED_EVENT_DESCRIPTOR,
  TOOL_CALL_EVENT_DESCRIPTOR,
  TOOL_EXECUTION_END_EVENT_DESCRIPTOR,
  TOOL_EXECUTION_START_EVENT_DESCRIPTOR,
  TOOL_OUTPUT_DISTILLED_EVENT_DESCRIPTOR,
  TOOL_RESULT_RECORDED_EVENT_DESCRIPTOR,
  readToolCallBlockedEventPayload,
  readToolLifecycleEventPayload,
  readToolOutputDistilledEventPayload,
  readToolResultRecordedEventPayload,
} from "../domain/tools/event-descriptors.js";
import {
  VERIFICATION_EVENT_DESCRIPTORS,
  VERIFICATION_OUTCOME_RECORDED_EVENT_DESCRIPTOR,
  VERIFICATION_WRITE_MARKED_EVENT_DESCRIPTOR,
  readVerificationOutcomeRecordedEventPayload,
  readVerificationWriteMarkedEventPayload,
} from "../domain/verification/event-descriptors.js";
import {
  WORKBENCH_BASELINE_COMMITTED_EVENT_DESCRIPTOR,
  WORKBENCH_EVENT_DESCRIPTORS,
  WORKBENCH_EVICTION_RECORDED_EVENT_DESCRIPTOR,
  WORKBENCH_EVICTION_UNDONE_EVENT_DESCRIPTOR,
  WORKBENCH_NOTE_RECORDED_EVENT_DESCRIPTOR,
  readWorkbenchBaselineCommittedEventPayload,
  readWorkbenchEvictionRecordedEventPayload,
  readWorkbenchEvictionUndoneEventPayload,
  readWorkbenchNoteRecordedEventPayload,
} from "../domain/workbench/event-descriptors.js";
import {
  asTypedBrewvaEventRecord,
  readBrewvaEventPayload,
  type BrewvaEventDescriptor,
  type BrewvaEventDescriptorPayload,
  type BrewvaTypedEventRecord,
} from "./descriptor-core.js";

export const BREWVA_TYPED_EVENT_DESCRIPTORS = [
  ...SESSIONS_EVENT_DESCRIPTORS,
  ...PROPOSALS_EVENT_DESCRIPTORS,
  ...TOOLS_EVENT_DESCRIPTORS,
  ...SKILLS_EVENT_DESCRIPTORS,
  ...VERIFICATION_EVENT_DESCRIPTORS,
  ...WORKBENCH_EVENT_DESCRIPTORS,
  ...TASK_EVENT_DESCRIPTORS,
  ...REASONING_EVENT_DESCRIPTORS,
  ...DELEGATION_EVENT_DESCRIPTORS,
  ...SESSION_LINEAGE_EVENT_DESCRIPTORS,
] as const;

export {
  asTypedBrewvaEventRecord,
  CAPABILITY_STATE_RECORDED_EVENT_DESCRIPTOR,
  CONTEXT_ENTRY_RECORDED_EVENT_DESCRIPTOR,
  DECISION_RECEIPT_RECORDED_EVENT_DESCRIPTOR,
  EFFECT_COMMITMENT_APPROVAL_CONSUMED_EVENT_DESCRIPTOR,
  EFFECT_COMMITMENT_APPROVAL_DECIDED_EVENT_DESCRIPTOR,
  EFFECT_COMMITMENT_APPROVAL_REQUESTED_EVENT_DESCRIPTOR,
  REASONING_REVERT_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_NODE_CREATED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_OUTCOME_ADOPTED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_OUTCOME_RECORDED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_SELECTION_RECORDED_EVENT_DESCRIPTOR,
  SESSION_LINEAGE_SUMMARY_RECORDED_EVENT_DESCRIPTOR,
  SESSION_REWIND_COMPLETED_EVENT_DESCRIPTOR,
  SESSION_TITLE_RECORDED_EVENT_DESCRIPTOR,
  SESSION_TURN_TRANSITION_EVENT_DESCRIPTOR,
  SESSION_UNCLEAN_SHUTDOWN_RECONCILED_EVENT_DESCRIPTOR,
  SUBAGENT_CANCELLED_EVENT_DESCRIPTOR,
  SUBAGENT_COMPLETED_EVENT_DESCRIPTOR,
  SUBAGENT_DELIVERY_SURFACED_EVENT_DESCRIPTOR,
  SUBAGENT_FAILED_EVENT_DESCRIPTOR,
  SUBAGENT_OUTCOME_PARSE_FAILED_EVENT_DESCRIPTOR,
  SUBAGENT_RUNNING_EVENT_DESCRIPTOR,
  SUBAGENT_SPAWNED_EVENT_DESCRIPTOR,
  TASK_STALL_ADJUDICATED_EVENT_DESCRIPTOR,
  TASK_STUCK_DETECTED_EVENT_DESCRIPTOR,
  TOOL_CALL_BLOCKED_EVENT_DESCRIPTOR,
  TOOL_CALL_EVENT_DESCRIPTOR,
  TOOL_EXECUTION_END_EVENT_DESCRIPTOR,
  TOOL_EXECUTION_START_EVENT_DESCRIPTOR,
  TOOL_OUTPUT_DISTILLED_EVENT_DESCRIPTOR,
  TOOL_RESULT_RECORDED_EVENT_DESCRIPTOR,
  TURN_INPUT_RECORDED_EVENT_DESCRIPTOR,
  TURN_RENDER_COMMITTED_EVENT_DESCRIPTOR,
  VERIFICATION_OUTCOME_RECORDED_EVENT_DESCRIPTOR,
  VERIFICATION_WRITE_MARKED_EVENT_DESCRIPTOR,
  WORKBENCH_BASELINE_COMMITTED_EVENT_DESCRIPTOR,
  WORKBENCH_EVICTION_RECORDED_EVENT_DESCRIPTOR,
  WORKBENCH_EVICTION_UNDONE_EVENT_DESCRIPTOR,
  WORKBENCH_NOTE_RECORDED_EVENT_DESCRIPTOR,
  WORKER_RESULTS_APPLIED_EVENT_DESCRIPTOR,
  readCapabilityStateRecordedEventPayload,
  readBrewvaEventPayload,
  readContextEntryRecordedEventPayload,
  readDelegationLifecycleEventPayload,
  readEffectCommitmentApprovalRequestedEventPayload,
  readEffectCommitmentApprovalResolutionEventPayload,
  readEffectCommitmentDecisionReceiptRecordedEventPayload,
  readReasoningRevertEventPayload,
  readSessionLineageNodeCreatedEventPayload,
  readSessionLineageOutcomeAdoptedEventPayload,
  readSessionLineageOutcomeRecordedEventPayload,
  readSessionLineageSelectionRecordedEventPayload,
  readSessionLineageSummaryRecordedEventPayload,
  readSessionRewindCompletedEventPayload,
  readSessionTitleRecordedEventPayload,
  readSessionTurnTransitionEventPayload,
  readSessionUncleanShutdownDiagnosticEventPayload,
  readTaskStallAdjudicatedEventPayload,
  readTaskStuckDetectedEventPayload,
  readToolCallBlockedEventPayload,
  readToolLifecycleEventPayload,
  readToolOutputDistilledEventPayload,
  readToolResultRecordedEventPayload,
  readTurnInputRecordedEventPayload,
  readTurnRenderCommittedEventPayload,
  readVerificationOutcomeRecordedEventPayload,
  readVerificationWriteMarkedEventPayload,
  readWorkbenchBaselineCommittedEventPayload,
  readWorkbenchEvictionRecordedEventPayload,
  readWorkbenchEvictionUndoneEventPayload,
  readWorkbenchNoteRecordedEventPayload,
  readWorkerResultsAppliedEventPayload,
};

export type { BrewvaEventDescriptor, BrewvaEventDescriptorPayload, BrewvaTypedEventRecord };
