import { CAPABILITIES_UNTYPED_EVENT_DEFINITIONS } from "../domain/capabilities/event-descriptors.js";
import { CAPABILITY_SELECTION_RECORDED_EVENT_TYPE } from "../domain/capabilities/events.js";
import { CHANNEL_EVENT_DEFINITIONS } from "../domain/channels/event-descriptors.js";
import {
  CHANNEL_COMMAND_RECEIVED_EVENT_TYPE,
  CHANNEL_SESSION_BOUND_EVENT_TYPE,
  CHANNEL_UPDATE_LOCK_BLOCKED_EVENT_TYPE,
  CHANNEL_UPDATE_REQUESTED_EVENT_TYPE,
  GATEWAY_SESSION_BOUND_EVENT_TYPE,
} from "../domain/channels/events.js";
import { CLAIM_UNTYPED_EVENT_DEFINITIONS } from "../domain/claim/event-descriptors.js";
import { CLAIM_EVENT_TYPE } from "../domain/claim/events.js";
import { CONTEXT_EVENT_DEFINITIONS } from "../domain/context/event-descriptors.js";
import {
  CONTEXT_COMPACTION_ADVISORY_EVENT_TYPE,
  CONTEXT_COMPACTION_AUTO_COMPLETED_EVENT_TYPE,
  CONTEXT_COMPACTION_AUTO_FAILED_EVENT_TYPE,
  CONTEXT_COMPACTION_AUTO_REQUESTED_EVENT_TYPE,
  CONTEXT_COMPACTION_GATE_ARMED_EVENT_TYPE,
  CONTEXT_COMPACTION_GATE_BLOCKED_TOOL_EVENT_TYPE,
  CONTEXT_COMPACTION_GATE_CLEARED_EVENT_TYPE,
  CONTEXT_COMPACTION_REQUESTED_EVENT_TYPE,
  CONTEXT_COMPACTION_SKIPPED_EVENT_TYPE,
  CONTEXT_COMPOSED_EVENT_TYPE,
  CONTEXT_USAGE_EVENT_TYPE,
  IDENTITY_PARSE_WARNING_EVENT_TYPE,
  COMPACTION_INTEGRITY_VIOLATION_EVENT_TYPE,
} from "../domain/context/events.js";
import { CONVENTIONS_UNTYPED_EVENT_DEFINITIONS } from "../domain/conventions/event-descriptors.js";
import {
  CONVENTION_CANDIDATE_OBSERVED_EVENT_TYPE,
  CONVENTION_CHANGE_APPLIED_EVENT_TYPE,
  CONVENTION_CHANGE_DECIDED_EVENT_TYPE,
  CONVENTION_CHANGE_REQUESTED_EVENT_TYPE,
  CONVENTION_CONFLICT_DETECTED_EVENT_TYPE,
  CONVENTION_CONTESTED_EVENT_TYPE,
  CONVENTION_DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  CONVENTION_EMERGENCY_APPLIED_EVENT_TYPE,
  CONVENTION_HEALTH_DEGRADED_EVENT_TYPE,
} from "../domain/conventions/events.js";
import { COST_EVENT_DEFINITIONS } from "../domain/cost/event-descriptors.js";
import { BUDGET_ALERT_EVENT_TYPE, COST_UPDATE_EVENT_TYPE } from "../domain/cost/events.js";
import { DELEGATION_UNTYPED_EVENT_DEFINITIONS } from "../domain/delegation/event-descriptors.js";
import {
  SUBAGENT_CANCELLED_EVENT_TYPE,
  SUBAGENT_A2A_MESSAGE_EVENT_TYPE,
  SUBAGENT_COMPLETED_EVENT_TYPE,
  SUBAGENT_DELIVERY_SURFACED_EVENT_TYPE,
  SUBAGENT_FAILED_EVENT_TYPE,
  SUBAGENT_KNOWLEDGE_ADOPTION_RECORDED_EVENT_TYPE,
  SUBAGENT_OUTCOME_PARSE_FAILED_EVENT_TYPE,
  SUBAGENT_RUNNING_EVENT_TYPE,
  SUBAGENT_SPAWNED_EVENT_TYPE,
  WORKER_RESULTS_APPLIED_EVENT_TYPE,
  WORKER_RESULTS_APPLY_FAILED_EVENT_TYPE,
} from "../domain/delegation/events.js";
import { ITERATION_EVENT_DEFINITIONS } from "../domain/events/iteration-event-descriptors.js";
import {
  ITERATION_GUARD_RECORDED_EVENT_TYPE,
  ITERATION_METRIC_OBSERVED_EVENT_TYPE,
} from "../domain/events/iteration-events.js";
import { GOVERNANCE_EVENT_DEFINITIONS } from "../domain/governance/event-descriptors.js";
import {
  EFFECT_AUTHORITY_DECIDED_EVENT_TYPE,
  GOVERNANCE_COMPACTION_INTEGRITY_CHECKED_EVENT_TYPE,
  GOVERNANCE_COMPACTION_INTEGRITY_ERROR_EVENT_TYPE,
  GOVERNANCE_COMPACTION_INTEGRITY_FAILED_EVENT_TYPE,
  GOVERNANCE_COST_ANOMALY_DETECTED_EVENT_TYPE,
  GOVERNANCE_COST_ANOMALY_ERROR_EVENT_TYPE,
  GOVERNANCE_METADATA_MISSING_EVENT_TYPE,
  GOVERNANCE_VERIFY_SPEC_ERROR_EVENT_TYPE,
  GOVERNANCE_VERIFY_SPEC_FAILED_EVENT_TYPE,
  GOVERNANCE_VERIFY_SPEC_PASSED_EVENT_TYPE,
  OPERATOR_QUESTION_ANSWERED_EVENT_TYPE,
  STEER_APPLIED_EVENT_TYPE,
  STEER_DROPPED_EVENT_TYPE,
  STEER_QUEUED_EVENT_TYPE,
  TOOL_EFFECT_GATE_SELECTED_EVENT_TYPE,
} from "../domain/governance/events.js";
import { LEDGER_EVENT_DEFINITIONS } from "../domain/ledger/event-descriptors.js";
import { LEDGER_COMPACTED_EVENT_TYPE } from "../domain/ledger/events.js";
import { LIFECYCLE_EVENT_DEFINITIONS } from "../domain/lifecycle/event-descriptors.js";
import {
  AGENT_END_EVENT_TYPE,
  MESSAGE_END_EVENT_TYPE,
  MODEL_PRESET_SELECT_EVENT_TYPE,
  MODEL_SELECT_EVENT_TYPE,
  SESSION_BEFORE_COMPACT_EVENT_TYPE,
  SESSION_BOOTSTRAP_EVENT_TYPE,
  SESSION_COMPACT_EVENT_TYPE,
  SESSION_COMPACT_FAILED_EVENT_TYPE,
  SESSION_COMPACT_REQUESTED_EVENT_TYPE,
  SESSION_COMPACT_REQUEST_FAILED_EVENT_TYPE,
  SESSION_REWIND_CHECKPOINT_RECORDED_EVENT_TYPE,
  SESSION_REWIND_REDO_COMPLETED_EVENT_TYPE,
  SESSION_REWIND_SUPERSEDED_EVENT_TYPE,
  SESSION_SHUTDOWN_EVENT_TYPE,
  SESSION_START_EVENT_TYPE,
  TURN_END_EVENT_TYPE,
  TURN_START_EVENT_TYPE,
} from "../domain/lifecycle/events.js";
import { PARALLEL_EVENT_DEFINITIONS } from "../domain/parallel/event-descriptors.js";
import {
  RESOURCE_LEASE_CANCELLED_EVENT_TYPE,
  RESOURCE_LEASE_EXPIRED_EVENT_TYPE,
  RESOURCE_LEASE_GRANTED_EVENT_TYPE,
  PARALLEL_SLOT_REJECTED_EVENT_TYPE,
} from "../domain/parallel/events.js";
import { PATCHING_EVENT_DEFINITIONS } from "../domain/patching/event-descriptors.js";
import {
  FILE_SNAPSHOT_CAPTURED_EVENT_TYPE,
  PATCH_RECORDED_EVENT_TYPE,
  REDO_EVENT_TYPE,
  REVERSIBLE_MUTATION_PREPARED_EVENT_TYPE,
  REVERSIBLE_MUTATION_RECORDED_EVENT_TYPE,
  REVERSIBLE_MUTATION_REDONE_EVENT_TYPE,
  REVERSIBLE_MUTATION_ROLLED_BACK_EVENT_TYPE,
  ROLLBACK_EVENT_TYPE,
} from "../domain/patching/events.js";
import { PROJECTION_EVENT_DEFINITIONS } from "../domain/projection/event-descriptors.js";
import {
  PROJECTION_INGESTED_EVENT_TYPE,
  PROJECTION_REFRESHED_EVENT_TYPE,
} from "../domain/projection/events.js";
import { PROPOSALS_UNTYPED_EVENT_DEFINITIONS } from "../domain/proposals/event-descriptors.js";
import {
  DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_CONSUMED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_DECIDED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_REQUESTED_EVENT_TYPE,
  PROPOSAL_DECIDED_EVENT_TYPE,
  PROPOSAL_RECEIVED_EVENT_TYPE,
  TURN_GOVERNANCE_DECISION_EVENT_TYPE,
} from "../domain/proposals/events.js";
import { REASONING_UNTYPED_EVENT_DEFINITIONS } from "../domain/reasoning/event-descriptors.js";
import { RECOVERY_EVENT_DEFINITIONS } from "../domain/recovery/event-descriptors.js";
import {
  CRITICAL_WITHOUT_COMPACT_EVENT_TYPE,
  RECOVERY_WAL_APPENDED_EVENT_TYPE,
  RECOVERY_WAL_COMPACTED_EVENT_TYPE,
  RECOVERY_WAL_RECOVERY_COMPLETED_EVENT_TYPE,
  RECOVERY_WAL_STATUS_CHANGED_EVENT_TYPE,
} from "../domain/recovery/events.js";
import { SCHEDULE_EVENT_DEFINITIONS } from "../domain/schedule/event-descriptors.js";
import { SCHEDULE_EVENT_TYPE } from "../domain/schedule/events.js";
import {
  SCHEDULE_CHILD_SESSION_FAILED_EVENT_TYPE,
  SCHEDULE_CHILD_SESSION_FINISHED_EVENT_TYPE,
  SCHEDULE_CHILD_SESSION_STARTED_EVENT_TYPE,
  SCHEDULE_RECOVERY_DEFERRED_EVENT_TYPE,
  SCHEDULE_RECOVERY_SUMMARY_EVENT_TYPE,
  SCHEDULE_TRIGGER_APPLY_WARNING_EVENT_TYPE,
  SCHEDULE_WAKEUP_EVENT_TYPE,
} from "../domain/schedule/events.js";
import {
  CAPABILITY_STATE_RECORDED_EVENT_TYPE,
  CONTEXT_ENTRY_RECORDED_EVENT_TYPE,
  SESSION_LINEAGE_NODE_CREATED_EVENT_TYPE,
  SESSION_LINEAGE_OUTCOME_ADOPTED_EVENT_TYPE,
  SESSION_LINEAGE_OUTCOME_RECORDED_EVENT_TYPE,
  SESSION_LINEAGE_SELECTION_RECORDED_EVENT_TYPE,
  SESSION_LINEAGE_SUMMARY_RECORDED_EVENT_TYPE,
  SESSION_REWIND_COMPLETED_EVENT_TYPE,
  SESSION_TITLE_RECORDED_EVENT_TYPE,
  SESSION_TURN_TRANSITION_EVENT_TYPE,
  SESSION_UNCLEAN_SHUTDOWN_RECONCILED_EVENT_TYPE,
  TURN_INPUT_RECORDED_EVENT_TYPE,
  TURN_RENDER_COMMITTED_EVENT_TYPE,
} from "../domain/sessions/events.js";
import { SKILLS_UNTYPED_EVENT_DEFINITIONS } from "../domain/skills/event-descriptors.js";
import { SKILL_REFRESH_RECORDED_EVENT_TYPE } from "../domain/skills/events.js";
import { TAPE_EVENT_DEFINITIONS } from "../domain/tape/event-descriptors.js";
import { TAPE_ANCHOR_EVENT_TYPE, TAPE_CHECKPOINT_EVENT_TYPE } from "../domain/tape/events.js";
import {
  TASK_LEDGER_EVENT_DEFINITIONS,
  TASK_UNTYPED_EVENT_DEFINITIONS,
} from "../domain/task/event-descriptors.js";
import {
  TASK_EVENT_TYPE,
  TASK_STALL_ADJUDICATED_EVENT_TYPE,
  TASK_STALL_ADJUDICATION_ERROR_EVENT_TYPE,
  TASK_STUCK_CLEARED_EVENT_TYPE,
  TASK_STUCK_DETECTED_EVENT_TYPE,
} from "../domain/task/events.js";
import { TOOLS_UNTYPED_EVENT_DEFINITIONS } from "../domain/tools/event-descriptors.js";
import {
  BOX_ACQUIRED_EVENT_TYPE,
  BOX_BOOTSTRAP_COMPLETED_EVENT_TYPE,
  BOX_BOOTSTRAP_FAILED_EVENT_TYPE,
  BOX_BOOTSTRAP_PROGRESS_EVENT_TYPE,
  BOX_BOOTSTRAP_STARTED_EVENT_TYPE,
  BOX_EXEC_COMPLETED_EVENT_TYPE,
  BOX_EXEC_FAILED_EVENT_TYPE,
  BOX_EXEC_STARTED_EVENT_TYPE,
  BOX_FORK_CREATED_EVENT_TYPE,
  BOX_MAINTENANCE_COMPLETED_EVENT_TYPE,
  BOX_RELEASED_EVENT_TYPE,
  BOX_SNAPSHOT_CREATED_EVENT_TYPE,
  TOOL_ATTEMPT_BINDING_MISSING_EVENT_TYPE,
  TOOL_CALL_BLOCKED_EVENT_TYPE,
  TOOL_CALL_EVENT_TYPE,
  TOOL_CALL_MARKED_EVENT_TYPE,
  TOOL_CONTRACT_WARNING_EVENT_TYPE,
  TOOL_EXECUTION_END_EVENT_TYPE,
  TOOL_EXECUTION_START_EVENT_TYPE,
  TOOL_OUTPUT_ARTIFACT_PERSISTED_EVENT_TYPE,
  TOOL_OUTPUT_ARTIFACT_PERSIST_FAILED_EVENT_TYPE,
  TOOL_OUTPUT_DISTILLED_EVENT_TYPE,
  TOOL_OUTPUT_OBSERVED_EVENT_TYPE,
  TOOL_OUTPUT_SEARCH_EVENT_TYPE,
  TOOL_PARALLEL_READ_EVENT_TYPE,
  TOOL_READ_PATH_DISCOVERY_OBSERVED_EVENT_TYPE,
  TOOL_READ_PATH_GATE_ARMED_EVENT_TYPE,
  TOOL_RESULT_RECORDED_EVENT_TYPE,
  TOOL_SURFACE_RESOLVED_EVENT_TYPE,
} from "../domain/tools/events.js";
import { VERIFICATION_UNTYPED_EVENT_DEFINITIONS } from "../domain/verification/event-descriptors.js";
import {
  VERIFICATION_OUTCOME_RECORDED_EVENT_TYPE,
  VERIFICATION_STATE_RESET_EVENT_TYPE,
  VERIFICATION_WRITE_MARKED_EVENT_TYPE,
} from "../domain/verification/events.js";
import {
  WORKBENCH_BASELINE_COMMITTED_EVENT_TYPE,
  WORKBENCH_EVICTION_RECORDED_EVENT_TYPE,
  WORKBENCH_EVICTION_UNDONE_EVENT_TYPE,
  WORKBENCH_NOTE_RECORDED_EVENT_TYPE,
} from "../domain/workbench/events.js";
import type { BrewvaUntypedEventDefinition } from "./definition-core.js";
import { BREWVA_TYPED_EVENT_DESCRIPTORS } from "./descriptors.js";
import { EXEC_EVENT_DEFINITIONS } from "./exec-event-descriptors.js";
import {
  EVENT_LISTENER_ERROR_EVENT_TYPE,
  EXEC_FAILED_EVENT_TYPE,
  EXEC_STARTED_EVENT_TYPE,
} from "./exec-events.js";
import { KNOWLEDGE_EVENT_DEFINITIONS } from "./knowledge-event-descriptors.js";
import {
  RECALL_CURATION_RECORDED_EVENT_TYPE,
  RECALL_RESULTS_SURFACED_EVENT_TYPE,
  RECALL_UTILITY_OBSERVED_EVENT_TYPE,
} from "./knowledge-events.js";
import { OBSERVABILITY_EVENT_DEFINITIONS } from "./observability-event-descriptors.js";
import {
  OBSERVABILITY_ASSERTION_RECORDED_EVENT_TYPE,
  OBSERVABILITY_QUERY_EXECUTED_EVENT_TYPE,
} from "./observability-events.js";
import type { BrewvaEventCategory, BrewvaEventDurabilityClass } from "./types.js";

export {
  AGENT_END_EVENT_TYPE,
  BOX_ACQUIRED_EVENT_TYPE,
  BOX_BOOTSTRAP_COMPLETED_EVENT_TYPE,
  BOX_BOOTSTRAP_FAILED_EVENT_TYPE,
  BOX_BOOTSTRAP_PROGRESS_EVENT_TYPE,
  BOX_BOOTSTRAP_STARTED_EVENT_TYPE,
  BOX_EXEC_COMPLETED_EVENT_TYPE,
  BOX_EXEC_FAILED_EVENT_TYPE,
  BOX_EXEC_STARTED_EVENT_TYPE,
  BOX_FORK_CREATED_EVENT_TYPE,
  BOX_MAINTENANCE_COMPLETED_EVENT_TYPE,
  BOX_RELEASED_EVENT_TYPE,
  BOX_SNAPSHOT_CREATED_EVENT_TYPE,
  BUDGET_ALERT_EVENT_TYPE,
  CAPABILITY_SELECTION_RECORDED_EVENT_TYPE,
  CAPABILITY_STATE_RECORDED_EVENT_TYPE,
  CHANNEL_COMMAND_RECEIVED_EVENT_TYPE,
  CHANNEL_SESSION_BOUND_EVENT_TYPE,
  CHANNEL_UPDATE_LOCK_BLOCKED_EVENT_TYPE,
  CHANNEL_UPDATE_REQUESTED_EVENT_TYPE,
  COMPACTION_INTEGRITY_VIOLATION_EVENT_TYPE,
  CONTEXT_COMPACTION_ADVISORY_EVENT_TYPE,
  CONTEXT_COMPACTION_AUTO_COMPLETED_EVENT_TYPE,
  CONTEXT_COMPACTION_AUTO_FAILED_EVENT_TYPE,
  CONTEXT_COMPACTION_AUTO_REQUESTED_EVENT_TYPE,
  CONTEXT_COMPACTION_GATE_ARMED_EVENT_TYPE,
  CONTEXT_COMPACTION_GATE_BLOCKED_TOOL_EVENT_TYPE,
  CONTEXT_COMPACTION_GATE_CLEARED_EVENT_TYPE,
  CONTEXT_COMPACTION_REQUESTED_EVENT_TYPE,
  CONTEXT_COMPACTION_SKIPPED_EVENT_TYPE,
  CONTEXT_COMPOSED_EVENT_TYPE,
  CONTEXT_ENTRY_RECORDED_EVENT_TYPE,
  CONTEXT_USAGE_EVENT_TYPE,
  CONVENTION_CANDIDATE_OBSERVED_EVENT_TYPE,
  CONVENTION_CHANGE_APPLIED_EVENT_TYPE,
  CONVENTION_CHANGE_DECIDED_EVENT_TYPE,
  CONVENTION_CHANGE_REQUESTED_EVENT_TYPE,
  CONVENTION_CONFLICT_DETECTED_EVENT_TYPE,
  CONVENTION_CONTESTED_EVENT_TYPE,
  CONVENTION_DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  CONVENTION_EMERGENCY_APPLIED_EVENT_TYPE,
  CONVENTION_HEALTH_DEGRADED_EVENT_TYPE,
  COST_UPDATE_EVENT_TYPE,
  CRITICAL_WITHOUT_COMPACT_EVENT_TYPE,
  DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  EFFECT_AUTHORITY_DECIDED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_CONSUMED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_DECIDED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_REQUESTED_EVENT_TYPE,
  EVENT_LISTENER_ERROR_EVENT_TYPE,
  EXEC_FAILED_EVENT_TYPE,
  EXEC_STARTED_EVENT_TYPE,
  FILE_SNAPSHOT_CAPTURED_EVENT_TYPE,
  GATEWAY_SESSION_BOUND_EVENT_TYPE,
  GOVERNANCE_COMPACTION_INTEGRITY_CHECKED_EVENT_TYPE,
  GOVERNANCE_COMPACTION_INTEGRITY_ERROR_EVENT_TYPE,
  GOVERNANCE_COMPACTION_INTEGRITY_FAILED_EVENT_TYPE,
  GOVERNANCE_COST_ANOMALY_DETECTED_EVENT_TYPE,
  GOVERNANCE_COST_ANOMALY_ERROR_EVENT_TYPE,
  GOVERNANCE_METADATA_MISSING_EVENT_TYPE,
  GOVERNANCE_VERIFY_SPEC_ERROR_EVENT_TYPE,
  GOVERNANCE_VERIFY_SPEC_FAILED_EVENT_TYPE,
  GOVERNANCE_VERIFY_SPEC_PASSED_EVENT_TYPE,
  IDENTITY_PARSE_WARNING_EVENT_TYPE,
  ITERATION_GUARD_RECORDED_EVENT_TYPE,
  ITERATION_METRIC_OBSERVED_EVENT_TYPE,
  LEDGER_COMPACTED_EVENT_TYPE,
  MESSAGE_END_EVENT_TYPE,
  MODEL_PRESET_SELECT_EVENT_TYPE,
  MODEL_SELECT_EVENT_TYPE,
  OBSERVABILITY_ASSERTION_RECORDED_EVENT_TYPE,
  OBSERVABILITY_QUERY_EXECUTED_EVENT_TYPE,
  OPERATOR_QUESTION_ANSWERED_EVENT_TYPE,
  PARALLEL_SLOT_REJECTED_EVENT_TYPE,
  PATCH_RECORDED_EVENT_TYPE,
  PROJECTION_INGESTED_EVENT_TYPE,
  PROJECTION_REFRESHED_EVENT_TYPE,
  PROPOSAL_DECIDED_EVENT_TYPE,
  PROPOSAL_RECEIVED_EVENT_TYPE,
  RECALL_CURATION_RECORDED_EVENT_TYPE,
  RECALL_RESULTS_SURFACED_EVENT_TYPE,
  RECALL_UTILITY_OBSERVED_EVENT_TYPE,
  RECOVERY_WAL_APPENDED_EVENT_TYPE,
  RECOVERY_WAL_COMPACTED_EVENT_TYPE,
  RECOVERY_WAL_RECOVERY_COMPLETED_EVENT_TYPE,
  RECOVERY_WAL_STATUS_CHANGED_EVENT_TYPE,
  REDO_EVENT_TYPE,
  RESOURCE_LEASE_CANCELLED_EVENT_TYPE,
  RESOURCE_LEASE_EXPIRED_EVENT_TYPE,
  RESOURCE_LEASE_GRANTED_EVENT_TYPE,
  REVERSIBLE_MUTATION_PREPARED_EVENT_TYPE,
  REVERSIBLE_MUTATION_RECORDED_EVENT_TYPE,
  REVERSIBLE_MUTATION_REDONE_EVENT_TYPE,
  REVERSIBLE_MUTATION_ROLLED_BACK_EVENT_TYPE,
  ROLLBACK_EVENT_TYPE,
  SCHEDULE_CHILD_SESSION_FAILED_EVENT_TYPE,
  SCHEDULE_CHILD_SESSION_FINISHED_EVENT_TYPE,
  SCHEDULE_CHILD_SESSION_STARTED_EVENT_TYPE,
  SCHEDULE_EVENT_TYPE,
  SCHEDULE_RECOVERY_DEFERRED_EVENT_TYPE,
  SCHEDULE_RECOVERY_SUMMARY_EVENT_TYPE,
  SCHEDULE_TRIGGER_APPLY_WARNING_EVENT_TYPE,
  SCHEDULE_WAKEUP_EVENT_TYPE,
  SESSION_BEFORE_COMPACT_EVENT_TYPE,
  SESSION_BOOTSTRAP_EVENT_TYPE,
  SESSION_COMPACT_EVENT_TYPE,
  SESSION_COMPACT_FAILED_EVENT_TYPE,
  SESSION_COMPACT_REQUESTED_EVENT_TYPE,
  SESSION_COMPACT_REQUEST_FAILED_EVENT_TYPE,
  SESSION_LINEAGE_NODE_CREATED_EVENT_TYPE,
  SESSION_LINEAGE_OUTCOME_ADOPTED_EVENT_TYPE,
  SESSION_LINEAGE_OUTCOME_RECORDED_EVENT_TYPE,
  SESSION_LINEAGE_SELECTION_RECORDED_EVENT_TYPE,
  SESSION_LINEAGE_SUMMARY_RECORDED_EVENT_TYPE,
  SESSION_REWIND_CHECKPOINT_RECORDED_EVENT_TYPE,
  SESSION_REWIND_COMPLETED_EVENT_TYPE,
  SESSION_REWIND_REDO_COMPLETED_EVENT_TYPE,
  SESSION_REWIND_SUPERSEDED_EVENT_TYPE,
  SESSION_SHUTDOWN_EVENT_TYPE,
  SESSION_START_EVENT_TYPE,
  SESSION_TITLE_RECORDED_EVENT_TYPE,
  SESSION_TURN_TRANSITION_EVENT_TYPE,
  SESSION_UNCLEAN_SHUTDOWN_RECONCILED_EVENT_TYPE,
  SKILL_REFRESH_RECORDED_EVENT_TYPE,
  STEER_APPLIED_EVENT_TYPE,
  STEER_DROPPED_EVENT_TYPE,
  STEER_QUEUED_EVENT_TYPE,
  SUBAGENT_A2A_MESSAGE_EVENT_TYPE,
  SUBAGENT_CANCELLED_EVENT_TYPE,
  SUBAGENT_COMPLETED_EVENT_TYPE,
  SUBAGENT_DELIVERY_SURFACED_EVENT_TYPE,
  SUBAGENT_FAILED_EVENT_TYPE,
  SUBAGENT_KNOWLEDGE_ADOPTION_RECORDED_EVENT_TYPE,
  SUBAGENT_OUTCOME_PARSE_FAILED_EVENT_TYPE,
  SUBAGENT_RUNNING_EVENT_TYPE,
  SUBAGENT_SPAWNED_EVENT_TYPE,
  TASK_EVENT_TYPE,
  TASK_STALL_ADJUDICATED_EVENT_TYPE,
  TASK_STALL_ADJUDICATION_ERROR_EVENT_TYPE,
  TASK_STUCK_CLEARED_EVENT_TYPE,
  TASK_STUCK_DETECTED_EVENT_TYPE,
  TAPE_ANCHOR_EVENT_TYPE,
  TAPE_CHECKPOINT_EVENT_TYPE,
  TOOL_ATTEMPT_BINDING_MISSING_EVENT_TYPE,
  TOOL_CALL_BLOCKED_EVENT_TYPE,
  TOOL_CALL_EVENT_TYPE,
  TOOL_CALL_MARKED_EVENT_TYPE,
  TOOL_CONTRACT_WARNING_EVENT_TYPE,
  TOOL_EFFECT_GATE_SELECTED_EVENT_TYPE,
  TOOL_EXECUTION_END_EVENT_TYPE,
  TOOL_EXECUTION_START_EVENT_TYPE,
  TOOL_OUTPUT_ARTIFACT_PERSISTED_EVENT_TYPE,
  TOOL_OUTPUT_ARTIFACT_PERSIST_FAILED_EVENT_TYPE,
  TOOL_OUTPUT_DISTILLED_EVENT_TYPE,
  TOOL_OUTPUT_OBSERVED_EVENT_TYPE,
  TOOL_OUTPUT_SEARCH_EVENT_TYPE,
  TOOL_PARALLEL_READ_EVENT_TYPE,
  TOOL_READ_PATH_DISCOVERY_OBSERVED_EVENT_TYPE,
  TOOL_READ_PATH_GATE_ARMED_EVENT_TYPE,
  TOOL_RESULT_RECORDED_EVENT_TYPE,
  TOOL_SURFACE_RESOLVED_EVENT_TYPE,
  CLAIM_EVENT_TYPE,
  TURN_END_EVENT_TYPE,
  TURN_GOVERNANCE_DECISION_EVENT_TYPE,
  TURN_INPUT_RECORDED_EVENT_TYPE,
  TURN_RENDER_COMMITTED_EVENT_TYPE,
  TURN_START_EVENT_TYPE,
  VERIFICATION_OUTCOME_RECORDED_EVENT_TYPE,
  VERIFICATION_STATE_RESET_EVENT_TYPE,
  VERIFICATION_WRITE_MARKED_EVENT_TYPE,
  WORKER_RESULTS_APPLIED_EVENT_TYPE,
  WORKER_RESULTS_APPLY_FAILED_EVENT_TYPE,
  WORKBENCH_BASELINE_COMMITTED_EVENT_TYPE,
  WORKBENCH_EVICTION_RECORDED_EVENT_TYPE,
  WORKBENCH_EVICTION_UNDONE_EVENT_TYPE,
  WORKBENCH_NOTE_RECORDED_EVENT_TYPE,
};

const BREWVA_UNTYPED_EVENT_DEFINITIONS = [
  ...CHANNEL_EVENT_DEFINITIONS,
  ...CAPABILITIES_UNTYPED_EVENT_DEFINITIONS,
  ...CONTEXT_EVENT_DEFINITIONS,
  ...CONVENTIONS_UNTYPED_EVENT_DEFINITIONS,
  ...COST_EVENT_DEFINITIONS,
  ...DELEGATION_UNTYPED_EVENT_DEFINITIONS,
  ...GOVERNANCE_EVENT_DEFINITIONS,
  ...LEDGER_EVENT_DEFINITIONS,
  ...LIFECYCLE_EVENT_DEFINITIONS,
  ...PARALLEL_EVENT_DEFINITIONS,
  ...PATCHING_EVENT_DEFINITIONS,
  ...PROPOSALS_UNTYPED_EVENT_DEFINITIONS,
  ...RECOVERY_EVENT_DEFINITIONS,
  ...REASONING_UNTYPED_EVENT_DEFINITIONS,
  ...SCHEDULE_EVENT_DEFINITIONS,
  ...SKILLS_UNTYPED_EVENT_DEFINITIONS,
  ...TAPE_EVENT_DEFINITIONS,
  ...TASK_UNTYPED_EVENT_DEFINITIONS,
  ...TASK_LEDGER_EVENT_DEFINITIONS,
  ...TOOLS_UNTYPED_EVENT_DEFINITIONS,
  ...CLAIM_UNTYPED_EVENT_DEFINITIONS,
  ...VERIFICATION_UNTYPED_EVENT_DEFINITIONS,
  ...ITERATION_EVENT_DEFINITIONS,
  ...PROJECTION_EVENT_DEFINITIONS,
  ...EXEC_EVENT_DEFINITIONS,
  ...KNOWLEDGE_EVENT_DEFINITIONS,
  ...OBSERVABILITY_EVENT_DEFINITIONS,
] as const;

type BrewvaTypedRegisteredEventType = (typeof BREWVA_TYPED_EVENT_DESCRIPTORS)[number]["type"];
type BrewvaUntypedRegisteredEventType = (typeof BREWVA_UNTYPED_EVENT_DEFINITIONS)[number]["type"];

export type BrewvaRegisteredEventType =
  | BrewvaTypedRegisteredEventType
  | BrewvaUntypedRegisteredEventType;

type BrewvaRegisteredEventMetadata =
  | (typeof BREWVA_TYPED_EVENT_DESCRIPTORS)[number]
  | BrewvaUntypedEventDefinition<BrewvaRegisteredEventType>;

function buildRegisteredEventMetadataByType(): ReadonlyMap<
  BrewvaRegisteredEventType,
  BrewvaRegisteredEventMetadata
> {
  const entries = new Map<BrewvaRegisteredEventType, BrewvaRegisteredEventMetadata>();
  for (const definition of [
    ...BREWVA_TYPED_EVENT_DESCRIPTORS,
    ...BREWVA_UNTYPED_EVENT_DEFINITIONS,
  ] as const) {
    const eventType = definition.type as BrewvaRegisteredEventType;
    if (entries.has(eventType)) {
      throw new Error(`duplicate_registered_event_type:${eventType}`);
    }
    entries.set(eventType, definition as BrewvaRegisteredEventMetadata);
  }
  return entries;
}

const BREWVA_EVENT_METADATA_BY_TYPE = buildRegisteredEventMetadataByType();

export const BREWVA_REGISTERED_EVENT_TYPES = [
  ...BREWVA_EVENT_METADATA_BY_TYPE.keys(),
] as readonly BrewvaRegisteredEventType[];

export const BREWVA_REGISTERED_EVENT_TYPE_SET: ReadonlySet<BrewvaRegisteredEventType> = new Set(
  BREWVA_REGISTERED_EVENT_TYPES,
);

function filterRegisteredEventTypesByDurability(
  durability: BrewvaEventDurabilityClass,
): readonly BrewvaRegisteredEventType[] {
  return BREWVA_REGISTERED_EVENT_TYPES.filter(
    (type) => BREWVA_EVENT_METADATA_BY_TYPE.get(type)?.durability === durability,
  );
}

export const BREWVA_SOURCE_OF_TRUTH_EVENT_TYPES =
  filterRegisteredEventTypesByDurability("source_of_truth");

export const BREWVA_REBUILDABLE_SIGNAL_EVENT_TYPES =
  filterRegisteredEventTypesByDurability("rebuildable_signal");

export const BREWVA_SESSION_LOCAL_EVENT_TYPES =
  filterRegisteredEventTypesByDurability("session_local");

export const BREWVA_DURABLE_EVIDENCE_EVENT_TYPES =
  filterRegisteredEventTypesByDurability("durable_evidence");

export const BREWVA_SESSION_LOCAL_EVENT_TYPE_SET: ReadonlySet<string> = new Set(
  BREWVA_SESSION_LOCAL_EVENT_TYPES,
);

export const BREWVA_EVENT_DURABILITY_BY_TYPE: Readonly<
  Record<BrewvaRegisteredEventType, BrewvaEventDurabilityClass>
> = Object.freeze(
  Object.fromEntries(
    BREWVA_REGISTERED_EVENT_TYPES.map((type) => {
      const durability = BREWVA_EVENT_METADATA_BY_TYPE.get(type)?.durability;
      if (!durability) {
        throw new Error(`registered_event_missing_durability:${type}`);
      }
      return [type, durability];
    }),
  ) as Record<BrewvaRegisteredEventType, BrewvaEventDurabilityClass>,
);

export const BREWVA_EVENT_CATEGORY_BY_TYPE: Readonly<
  Record<BrewvaRegisteredEventType, BrewvaEventCategory>
> = Object.freeze(
  Object.fromEntries(
    BREWVA_REGISTERED_EVENT_TYPES.map((type) => {
      const category = BREWVA_EVENT_METADATA_BY_TYPE.get(type)?.category;
      if (!category) {
        throw new Error(`registered_event_missing_category:${type}`);
      }
      return [type, category];
    }),
  ) as Record<BrewvaRegisteredEventType, BrewvaEventCategory>,
);

export function getBrewvaEventDurabilityClass(
  type: string,
): BrewvaEventDurabilityClass | undefined {
  return BREWVA_EVENT_METADATA_BY_TYPE.get(type as BrewvaRegisteredEventType)?.durability;
}

export function getBrewvaEventCategory(type: string): BrewvaEventCategory | undefined {
  return BREWVA_EVENT_METADATA_BY_TYPE.get(type as BrewvaRegisteredEventType)?.category;
}

export function isBrewvaRegisteredEventType(value: string): value is BrewvaRegisteredEventType {
  return BREWVA_REGISTERED_EVENT_TYPE_SET.has(value as BrewvaRegisteredEventType);
}
