export {
  canonicalEventToFourPortRuntimeEvent,
  createFourPortCostRuntimeOps,
  createFourPortEventsRuntimeOps,
  createFourPortLifecycleRuntimeOps,
  createFourPortRecoveryRuntimeOps,
  createFourPortTapeRuntimeOps,
  deriveTurnEffectCommitmentProjection,
  FOUR_PORT_RUNTIME_OPS_EVENT_NAMESPACES,
  listFourPortRuntimeEvents,
  recordFourPortRuntimeOpsEvent,
  renderTurnConsequenceDigest,
  structureFourPortRuntimeEvent,
  type FourPortRuntimeCapabilityContext,
  type FourPortRuntimeEventListener,
  type FourPortRuntimeEventRecord,
} from "./four-port-capabilities.js";
export {
  recordToolRuntimeEvent,
  registerToolRuntimeClearStateListener,
  resolveToolRuntimeCapabilitiesTools,
  resolveToolRuntimeContextPort,
  resolveToolRuntimeCredentialBindings,
  resolveToolRuntimeEventPort,
  resolveToolRuntimeTaskPort,
  type ToolRuntimeEventInput,
} from "./extensions.js";
export { blockGoal, completeGoal, getGoalState } from "./goal.js";
// The pure tape->fitness-input assembler, for the CLI operator surfaces to
// re-derive the CURRENT requirement fitness from the whole tape.
export {
  assembleRequirementFitnessInputFromEvents,
  buildTapeCoverageAttributionMiss,
  buildTapeRequirementDebtSummary,
  buildTapeRequirementFitness,
  buildTapeReviewDebt,
  buildTapeUnaddressedReviewFindings,
  buildTapeUnverifiedRequirementDebt,
  type TapeRequirementDebtSummary,
} from "./verification.js";
export {
  getToolSessionId,
  readTextBatch,
  recordParallelReadTelemetry,
  resolveAdaptiveBatchSize,
  resolveParallelReadConfig,
  summarizeReadBatch,
  withParallelReadSlot,
  type ParallelReadConfig,
  type ParallelReadMode,
  type ParallelReadReason,
  type ParallelReadSlotOptions,
  type ParallelReadTelemetry,
  type ReadBatchItem,
  type ReadBatchSummary,
  type ReadTextBatchOptions,
} from "./parallel-read.js";
export {
  describeRuntimeArtifactReadRejection,
  describeTargetScopeRejection,
  isPathInsideRoots,
  resolveReadableScopedPath,
  resolveRuntimeArtifactCommandRejection,
  resolveRuntimeArtifactReadRejection,
  resolveScopedPath,
  resolveToolTargetScope,
  TARGET_SCOPE_REJECTION_GUIDANCE,
  type RuntimeArtifactReadRejection,
  type RuntimeArtifactReadRejectionReason,
  type TargetScopeRejection,
  type ToolTargetScope,
} from "./target-scope.js";
