import type { DelegationRunRecord } from "@brewva/brewva-vocabulary/delegation";

export function buildDelegationLifecyclePayload(
  record: DelegationRunRecord,
): Record<string, unknown> {
  return {
    contractVersion: record.contractVersion,
    runId: record.runId,
    agent: record.agent,
    targetName: record.targetName,
    delegate: record.delegate,
    taskName: record.taskName,
    taskPath: record.taskPath,
    nickname: record.nickname,
    depth: record.depth,
    forkTurns: record.forkTurns,
    gateReason: record.gateReason,
    modelCategory: record.modelCategory,
    executionPrimitive: record.executionPrimitive,
    visibility: record.visibility,
    isolationStrategy: record.isolationStrategy,
    adoption: record.adoption,
    lineage: record.lineage ?? null,
    agentSpec: record.agentSpec ?? null,
    envelope: record.envelope ?? null,
    skillName: record.skillName ?? null,
    label: record.label ?? null,
    kind: record.kind ?? null,
    consultKind: record.consultKind ?? null,
    boundary: record.boundary ?? null,
    parentSkill: record.parentSkill ?? null,
    childSessionId: record.workerSessionId ?? null,
    status: record.status,
    summary: record.summary ?? null,
    error: record.error ?? null,
    resultData: record.resultData ?? null,
    artifactRefs: record.artifactRefs ?? [],
    totalTokens: record.totalTokens ?? null,
    costUsd: record.costUsd ?? null,
    modelRoute: record.modelRoute ?? null,
    deliveryMode: record.delivery?.mode ?? null,
    deliveryScopeId: record.delivery?.scopeId ?? null,
    deliveryLabel: record.delivery?.label ?? null,
    deliveryHandoffState: record.delivery?.handoffState ?? null,
    deliveryReadyAt: record.delivery?.readyAt ?? null,
    deliverySurfacedAt: record.delivery?.surfacedAt ?? null,
    supplementalAppended: record.delivery?.supplementalAppended ?? null,
    deliveryUpdatedAt: record.delivery?.updatedAt ?? null,
    createdAt: record.createdAt,
    updatedAt: record.updatedAt,
  };
}
