import type { ToolActionClass } from "@brewva/brewva-runtime/security";
import type { BrewvaToolRequiredCapability, BrewvaToolSurface } from "../contracts/index.js";

export interface ManagedBrewvaToolMetadataRegistryEntry {
  surface: BrewvaToolSurface;
  actionClass: ToolActionClass;
  requiredCapabilities?: readonly BrewvaToolRequiredCapability[];
}

function metadata<TSurface extends BrewvaToolSurface, TActionClass extends ToolActionClass>(
  surface: TSurface,
  actionClass: TActionClass,
): { surface: TSurface; actionClass: TActionClass };
function metadata<
  TSurface extends BrewvaToolSurface,
  TActionClass extends ToolActionClass,
  const TCapabilities extends readonly BrewvaToolRequiredCapability[],
>(
  surface: TSurface,
  actionClass: TActionClass,
  requiredCapabilities: TCapabilities,
): { surface: TSurface; actionClass: TActionClass; requiredCapabilities: TCapabilities };
function metadata(
  surface: BrewvaToolSurface,
  actionClass: ToolActionClass,
  requiredCapabilities?: readonly BrewvaToolRequiredCapability[],
): ManagedBrewvaToolMetadataRegistryEntry {
  return requiredCapabilities && requiredCapabilities.length > 0
    ? { surface, actionClass, requiredCapabilities }
    : { surface, actionClass };
}

export const MANAGED_BREWVA_TOOL_METADATA_BY_NAME = {
  agent_broadcast: metadata("operator", "external_side_effect"),
  agent_list: metadata("operator", "runtime_observe"),
  agent_send: metadata("operator", "external_side_effect"),
  grep: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.readPath.discoveryObserved",
    "capabilities.tools.sourcePatch.snapshots.record",
  ]),
  glob: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  git_status: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  git_diff: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  git_log: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  source_read: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.readPath.discoveryObserved",
    "capabilities.tools.sourcePatch.snapshots.record",
  ]),
  resource_read: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.sourcePatch.resources.read",
  ]),
  source_patch_prepare: metadata("skill", "workspace_patch", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.sourcePatch.plans.prepare",
    "capabilities.tools.sourcePatch.staleRecovery.record",
  ]),
  source_patch_apply: metadata("skill", "workspace_patch", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.sourcePatch.plans.apply",
  ]),
  look_at: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  discover_skills: metadata("base", "runtime_observe", [
    "capabilities.skills.catalog.list",
    "capabilities.skills.selection.record",
  ]),
  attention_options: metadata("base", "workspace_read", [
    "capabilities.skills.catalog.list",
    "capabilities.workbench.list",
    "capabilities.events.records.query",
    "capabilities.events.recordMetricObservation",
    "capabilities.task.target.getDescriptor",
  ]),
  attention_consume: metadata("base", "memory_write", [
    "capabilities.skills.catalog.get",
    "capabilities.workbench.list",
    "capabilities.events.records.query",
    "capabilities.events.iteration.listMetricObservations",
    "capabilities.events.recordMetricObservation",
  ]),
  attention_pin: metadata("base", "memory_write", ["capabilities.workbench.note"]),
  attention_ignore: metadata("base", "memory_write", [
    "capabilities.events.recordMetricObservation",
  ]),
  attention_verify_plan: metadata("base", "memory_write", [
    "capabilities.events.recordMetricObservation",
  ]),
  code_outline: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  code_digest: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  code_surface: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  code_deps: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  code_reverse_deps: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  code_cycles: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  code_callers: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  code_callees: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.sourceIntelligenceQuery",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  reasoning_checkpoint: metadata("control_plane", "control_state_mutation", [
    "capabilities.reasoning.checkpoints.record",
  ]),
  reasoning_revert: metadata("control_plane", "control_state_mutation", [
    "capabilities.reasoning.reverts.revert",
  ]),
  get_goal: metadata("control_plane", "runtime_observe", ["capabilities.goal.state.get"]),
  update_goal: metadata("control_plane", "control_state_mutation", [
    "capabilities.goal.state.get",
    "capabilities.goal.lifecycle.complete",
    "capabilities.goal.lifecycle.block",
  ]),
  workbench_compact: metadata("base", "memory_write", [
    "capabilities.context.compaction.getInstructions",
    "capabilities.context.usage.getRatio",
    "capabilities.session.lifecycle.compactFailed",
    "capabilities.session.lifecycle.compactRequested",
    "capabilities.session.lifecycle.compactRequestFailed",
    "capabilities.tools.outputs.observed",
  ]),
  resource_lease: metadata("base", "budget_mutation", [
    "capabilities.tools.resourceLeases.request",
    "capabilities.tools.resourceLeases.cancel",
    "capabilities.tools.resourceLeases.list",
  ]),
  exec: metadata("base", "local_exec_effectful", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "extensions.tools.onClearState",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.execution.recordAudit",
    "capabilities.tools.lifecycle.boxReleased",
    "extensions.tools.resolveCredentialBindings",
  ]),
  lsp_diagnostics: metadata("base", "workspace_read", [
    "capabilities.tools.parallel.acquireAsync",
    "capabilities.tools.parallel.release",
    "capabilities.tools.lifecycle.parallelRead",
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  process: metadata("base", "local_exec_effectful", [
    "extensions.tools.onClearState",
    "capabilities.tools.lifecycle.boxReleased",
    "capabilities.tools.outputs.observed",
  ]),
  workbench_note: metadata("base", "memory_write", ["capabilities.workbench.note"]),
  workbench_evict: metadata("base", "memory_write", [
    "capabilities.events.records.list",
    "capabilities.workbench.evict",
  ]),
  workbench_undo_evict: metadata("base", "memory_write", ["capabilities.workbench.undoEviction"]),
  knowledge_capture: metadata("skill", "workspace_patch", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  recall_search: metadata("skill", "workspace_read", [
    "capabilities.events.records.list",
    "capabilities.events.records.listSessionIds",
    "capabilities.events.records.query",
    "capabilities.events.records.subscribe",
    "capabilities.skills.catalog.getProducer",
    "capabilities.skills.catalog.getLoadReport",
    "capabilities.skills.catalog.list",
    "capabilities.skills.catalog.listProducers",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.recall.resultsSurfaced",
  ]),
  recall_curate: metadata("operator", "memory_write", [
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.recall.curationRecorded",
  ]),
  recall_expand: metadata("skill", "workspace_read", [
    "capabilities.events.records.list",
    "capabilities.workbench.list",
  ]),
  context_route: metadata("skill", "runtime_observe", []),
  knowledge_search: metadata("skill", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  precedent_audit: metadata("skill", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  precedent_sweep: metadata("skill", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  browser_open: metadata("skill", "local_exec_effectful", [
    "capabilities.tools.access.explain",
    "capabilities.tools.lifecycle.callBlocked",
    "capabilities.tools.outputs.observed",
  ]),
  browser_wait: metadata("skill", "local_exec_effectful"),
  browser_snapshot: metadata("skill", "local_exec_effectful"),
  browser_click: metadata("skill", "local_exec_effectful"),
  browser_fill: metadata("skill", "local_exec_effectful"),
  browser_get: metadata("skill", "local_exec_effectful"),
  browser_screenshot: metadata("skill", "local_exec_effectful"),
  browser_pdf: metadata("skill", "local_exec_effectful"),
  browser_diff_snapshot: metadata("skill", "local_exec_effectful"),
  browser_state_load: metadata("skill", "local_exec_effectful"),
  browser_state_save: metadata("skill", "local_exec_effectful"),
  browser_close: metadata("skill", "local_exec_effectful"),
  question: metadata("base", "runtime_observe"),
  tape_handoff: metadata("skill", "control_state_mutation", [
    "capabilities.tape.handoff.record",
    "capabilities.tape.status.get",
  ]),
  tape_info: metadata("control_plane", "runtime_observe", [
    "capabilities.context.usage.getStatus",
    "capabilities.context.usage.get",
    "capabilities.tape.status.get",
    "capabilities.reasoning.state.getActive",
  ]),
  tape_search: metadata("skill", "runtime_observe", ["capabilities.tape.search.search"]),
  task_view_state: metadata("control_plane", "runtime_observe", ["capabilities.task.state.get"]),
  ledger_query: metadata("control_plane", "runtime_observe", ["capabilities.ledger.store.query"]),
  lsp_status: metadata("base", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  lsp_hover: metadata("skill", "workspace_read", [
    "capabilities.tools.parallel.acquireAsync",
    "capabilities.tools.parallel.release",
    "capabilities.tools.lifecycle.parallelRead",
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  lsp_definition: metadata("skill", "workspace_read", [
    "capabilities.tools.parallel.acquireAsync",
    "capabilities.tools.parallel.release",
    "capabilities.tools.lifecycle.parallelRead",
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  lsp_references: metadata("skill", "workspace_read", [
    "capabilities.tools.parallel.acquireAsync",
    "capabilities.tools.parallel.release",
    "capabilities.tools.lifecycle.parallelRead",
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.readPath.discoveryObserved",
  ]),
  lsp_type_definition: metadata("skill", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  lsp_implementation: metadata("skill", "workspace_read", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
  ]),
  lsp_rename: metadata("skill", "workspace_patch", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.sourcePatch.snapshots.record",
    "capabilities.tools.sourcePatch.plans.prepare",
    "capabilities.tools.sourcePatch.staleRecovery.record",
  ]),
  lsp_file_rename: metadata("skill", "workspace_patch", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.sourcePatch.snapshots.record",
    "capabilities.tools.sourcePatch.plans.prepare",
    "capabilities.tools.sourcePatch.staleRecovery.record",
  ]),
  lsp_code_action: metadata("skill", "workspace_patch", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.sourcePatch.snapshots.record",
    "capabilities.tools.sourcePatch.plans.prepare",
    "capabilities.tools.sourcePatch.staleRecovery.record",
  ]),
  lsp_format: metadata("skill", "workspace_patch", [
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.tools.sourcePatch.snapshots.record",
    "capabilities.tools.sourcePatch.plans.prepare",
    "capabilities.tools.sourcePatch.staleRecovery.record",
  ]),
  output_search: metadata("skill", "workspace_read", [
    "capabilities.events.records.list",
    "capabilities.tools.outputs.observed",
    "capabilities.tools.outputs.search",
  ]),
  workflow_status: metadata("control_plane", "runtime_observe", [
    "capabilities.events.records.query",
    "capabilities.session.lifecycle.getOpenToolCalls",
    "capabilities.session.lifecycle.getUncleanShutdownDiagnostic",
    "capabilities.session.workerResults.list",
    "capabilities.task.state.get",
  ]),
  follow_up: metadata("skill", "schedule_mutation", [
    "capabilities.schedule.intents.cancel",
    "capabilities.schedule.intents.create",
    "capabilities.schedule.intents.getProjectionSnapshot",
    "capabilities.schedule.intents.list",
  ]),
  worker_results_merge: metadata("skill", "runtime_observe", [
    "capabilities.session.workerResults.merge",
  ]),
  worker_results_apply: metadata("skill", "workspace_patch", [
    "capabilities.delegation.workerResults.applied",
    "capabilities.delegation.workerResults.applyFailed",
    "capabilities.events.records.query",
    "capabilities.task.target.getDescriptor",
    "capabilities.session.workerResults.list",
    "capabilities.session.workerResults.clear",
    "capabilities.tools.sourcePatch.snapshots.record",
    "capabilities.tools.sourcePatch.plans.prepare",
    "capabilities.tools.sourcePatch.plans.apply",
  ]),
  worker_results_reject: metadata("skill", "control_state_mutation", [
    "capabilities.delegation.workerResults.rejected",
    "capabilities.session.workerResults.list",
    "capabilities.session.workerResults.clear",
  ]),
  schedule_intent: metadata("skill", "schedule_mutation", [
    "capabilities.schedule.intents.getProjectionSnapshot",
    "capabilities.schedule.intents.list",
    "capabilities.schedule.intents.create",
    "capabilities.schedule.intents.update",
    "capabilities.schedule.intents.cancel",
  ]),
  subagent_run: metadata("skill", "delegation"),
  subagent_fanout: metadata("skill", "delegation"),
  subagent_fork: metadata("skill", "delegation"),
  subagent_run_diagnostic: metadata("control_plane", "delegation"),
  subagent_status: metadata("skill", "delegation"),
  inbox_query: metadata("skill", "runtime_observe", ["capabilities.events.records.query"]),
  subagent_cancel: metadata("skill", "delegation"),
  subagent_knowledge_adopt: metadata("skill", "delegation", [
    "capabilities.delegation.lifecycle.knowledgeAdoptionRecorded",
  ]),
  task_add_item: metadata("control_plane", "memory_write", ["capabilities.task.items.add"]),
  task_record_acceptance: metadata("operator", "memory_write", [
    "capabilities.task.acceptance.record",
  ]),
  task_record_blocker: metadata("control_plane", "memory_write", [
    "capabilities.task.blockers.record",
  ]),
  task_resolve_blocker: metadata("control_plane", "memory_write", [
    "capabilities.task.blockers.resolve",
  ]),
  task_set_spec: metadata("control_plane", "memory_write", ["capabilities.task.spec.set"]),
  task_update_item: metadata("control_plane", "memory_write", ["capabilities.task.items.update"]),
  cost_view: metadata("operator", "runtime_observe", ["capabilities.cost.summary.get"]),
  obs_query: metadata("operator", "runtime_observe", [
    "capabilities.events.records.list",
    "capabilities.tools.observability.queryExecuted",
    "capabilities.tools.outputs.observed",
  ]),
  obs_slo_assert: metadata("operator", "runtime_observe", [
    "capabilities.events.records.list",
    "capabilities.tools.observability.queryExecuted",
    "capabilities.tools.observability.assertionRecorded",
    "capabilities.tools.outputs.observed",
  ]),
  obs_snapshot: metadata("operator", "runtime_observe", [
    "capabilities.context.usage.getStatus",
    "capabilities.context.evidence.latest",
    "capabilities.context.usage.get",
    "capabilities.cost.summary.get",
    "capabilities.tape.status.get",
    "capabilities.events.records.list",
    "capabilities.task.state.get",
  ]),
  iteration_fact: metadata("skill", "memory_write", [
    "capabilities.events.recordMetricObservation",
    "capabilities.events.recordGuardResult",
    "capabilities.events.iteration.listGuardResults",
    "capabilities.events.iteration.listMetricObservations",
  ]),
  rollback_last_patch: metadata("operator", "workspace_patch", [
    "capabilities.tools.patches.rollbackLastPatchSet",
  ]),
} as const satisfies Record<string, ManagedBrewvaToolMetadataRegistryEntry>;
