import {
  BREWVA_TOOL_RUNTIME_CAPABILITY_PATHS,
  type BrewvaToolRequiredCapability,
} from "../contracts/runtime-capabilities.js";

// Generated by `bun run tools:capability-inventory`. Source owns 156 paths.
const BREWVA_TOOL_RUNTIME_CAPABILITY_PATH_SET = new Set<string>(
  BREWVA_TOOL_RUNTIME_CAPABILITY_PATHS,
);

export { BREWVA_TOOL_RUNTIME_CAPABILITY_PATHS };

export function isBrewvaToolRuntimeCapabilityPath(
  capability: string,
): capability is BrewvaToolRequiredCapability {
  return BREWVA_TOOL_RUNTIME_CAPABILITY_PATH_SET.has(capability);
}
