import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import {
  ALL_RUNTIME_PLUGIN_CAPABILITIES,
  RUNTIME_PLUGIN_CAPABILITY_EFFECTS,
} from "@brewva/brewva-substrate/host-api";

// Derived-view generator for the host-plugin capability x plugin matrix.
//
// The capability set and effect classes are single-sourced in
// `RUNTIME_PLUGIN_CAPABILITY_EFFECTS` (brewva-substrate); each internal plugin's
// declared set is single-sourced at its definition. This script renders an
// authority inventory: capability -> effect class -> which plugins declare it.
// It is build-time tooling only: runtime packages must never import this script
// or read the generated view (axiom 18).

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const OUT_DOC = "docs/reference/host-plugin-capabilities.md";
const BLOCK_NAME = "host-plugin-capabilities";

interface InternalPlugin {
  readonly name: string;
  readonly capabilities: ReadonlySet<string>;
}

// Read the internal plugin's declared set from source text rather than importing
// gateway internals: this generator lives in the `script` TS project, which does
// not list gateway sources. The array is the single source of truth at its
// definition; a drift-guard fitness keeps doc and code in lockstep.
function readHostedBehaviorCapabilities(): readonly string[] {
  const source = readFileSync(
    resolve(
      repoRoot,
      "packages/brewva-gateway/src/hosted/internal/session/host-api-installation.ts",
    ),
    "utf-8",
  );
  const block = /export const HOSTED_BEHAVIOR_CAPABILITIES = \[([\s\S]*?)\] as const/u.exec(source);
  if (!block?.[1]) {
    throw new Error("HOSTED_BEHAVIOR_CAPABILITIES array not found in host-api-installation.ts");
  }
  return [...block[1].matchAll(/"([^"]+)"/gu)].map((entry) => entry[1]!);
}

const INTERNAL_PLUGINS: readonly InternalPlugin[] = [
  { name: "hosted_behavior", capabilities: new Set<string>(readHostedBehaviorCapabilities()) },
];

function render(): string {
  const capabilities = [...ALL_RUNTIME_PLUGIN_CAPABILITIES].toSorted();
  const header = [
    "Capability",
    "Effect class",
    ...INTERNAL_PLUGINS.map((plugin) => `\`${plugin.name}\``),
  ];
  const rows = capabilities.map((capability) => [
    `\`${capability}\``,
    `\`${RUNTIME_PLUGIN_CAPABILITY_EFFECTS[capability]}\``,
    ...INTERNAL_PLUGINS.map((plugin) => (plugin.capabilities.has(capability) ? "yes" : "no")),
  ]);
  // Emit an already-aligned table so the generated block is oxfmt-stable and the
  // regenerate-and-diff freshness check does not fight the formatter.
  const widths = header.map((_, column) =>
    Math.max(header[column]!.length, ...rows.map((row) => row[column]!.length)),
  );
  const renderRow = (cells: readonly string[]): string =>
    `| ${cells.map((cell, column) => cell.padEnd(widths[column]!)).join(" | ")} |`;
  const separator = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
  return [
    "> Generated by `bun run docs:host-plugin-capabilities`. Do not edit this block by hand.",
    "",
    `Capabilities: ${capabilities.length}. Internal plugins: ${INTERNAL_PLUGINS.length}.`,
    "",
    renderRow(header),
    separator,
    ...rows.map(renderRow),
  ]
    .join("\n")
    .trimEnd();
}

function replaceGeneratedBlock(markdown: string, content: string): string {
  const startMarker = `<!-- generated:${BLOCK_NAME} start -->`;
  const endMarker = `<!-- generated:${BLOCK_NAME} end -->`;
  const start = markdown.indexOf(startMarker);
  const end = markdown.indexOf(endMarker);
  if (start < 0 || end < 0 || end < start) {
    throw new Error(`Missing generated markers for ${BLOCK_NAME} in ${OUT_DOC}`);
  }
  const before = markdown.slice(0, start + startMarker.length);
  const after = markdown.slice(end);
  return `${before}\n\n${content}\n\n${after}`;
}

function main(): void {
  const { values } = parseArgs({
    options: {
      write: { type: "boolean", default: false },
      check: { type: "boolean", default: false },
    },
  });
  if (values.write === values.check) {
    throw new Error("Use exactly one mode: --write or --check.");
  }

  const docPath = resolve(repoRoot, OUT_DOC);
  const markdown = readFileSync(docPath, "utf-8").replace(/\r\n?/g, "\n");
  const next = replaceGeneratedBlock(markdown, render());
  const changed = next !== markdown;

  if (values.check && changed) {
    console.error(
      "Generated host-plugin-capabilities view is stale. Run `bun run docs:host-plugin-capabilities`.",
    );
    process.exitCode = 1;
    return;
  }
  if (values.write) {
    if (changed) {
      writeFileSync(docPath, next);
      console.log("Updated generated host-plugin-capabilities view.");
    } else {
      console.log("Generated host-plugin-capabilities view is already up to date.");
    }
  }
}

main();
