import { defineBrewvaUntypedEventDefinition } from "../../events/definition-core.js";
import {
  CONVENTION_CANDIDATE_OBSERVED_EVENT_TYPE,
  CONVENTION_CHANGE_APPLIED_EVENT_TYPE,
  CONVENTION_CHANGE_DECIDED_EVENT_TYPE,
  CONVENTION_CHANGE_REQUESTED_EVENT_TYPE,
  CONVENTION_CONFLICT_DETECTED_EVENT_TYPE,
  CONVENTION_CONTESTED_EVENT_TYPE,
  CONVENTION_DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  CONVENTION_EMERGENCY_APPLIED_EVENT_TYPE,
  CONVENTION_HEALTH_DEGRADED_EVENT_TYPE,
} from "./events.js";

export const CONVENTIONS_UNTYPED_EVENT_DEFINITIONS = [
  CONVENTION_CANDIDATE_OBSERVED_EVENT_TYPE,
  CONVENTION_CHANGE_REQUESTED_EVENT_TYPE,
  CONVENTION_CHANGE_DECIDED_EVENT_TYPE,
  CONVENTION_DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  CONVENTION_CHANGE_APPLIED_EVENT_TYPE,
  CONVENTION_CONFLICT_DETECTED_EVENT_TYPE,
  CONVENTION_HEALTH_DEGRADED_EVENT_TYPE,
  CONVENTION_CONTESTED_EVENT_TYPE,
  CONVENTION_EMERGENCY_APPLIED_EVENT_TYPE,
].map((type) =>
  defineBrewvaUntypedEventDefinition({
    type,
    category: "governance",
    durability: "source_of_truth",
  }),
);
