import type {
  ShellCommand,
  ShellCommandProvider,
  ShellSlashReservation,
} from "./command-provider.js";

const builtInShellCommands: readonly ShellCommand[] = [
  {
    id: "app.commandPalette",
    title: "Open command palette",
    description: "Search and run available Brewva TUI actions.",
    category: "System",
    discovery: { help: false },
    keybinding: { key: "k", ctrl: true, meta: false, shift: false },
    suggested: true,
  },
  {
    id: "app.help",
    title: "Help",
    description: "Open Brewva TUI help and discovery shortcuts.",
    category: "System",
    slash: { name: "help" },
    suggested: true,
  },
  {
    id: "app.exit",
    title: "Exit Brewva",
    description: "Exit the interactive shell.",
    category: "System",
    slash: { name: "quit", aliases: ["exit"], argumentMode: "none" },
    keybinding: { key: "q", ctrl: true, meta: false, shift: false },
  },
  {
    id: "app.abortOrExit",
    title: "Abort or exit",
    description: "Abort the current turn; exits when no turn is streaming.",
    category: "System",
    keybinding: { key: "c", ctrl: true, meta: false, shift: false },
  },
  {
    id: "composer.editor",
    title: "Open external editor",
    description: "Edit the current prompt in VISUAL or EDITOR.",
    category: "Composer",
    keybinding: { key: "e", ctrl: true, meta: false, shift: false },
  },
  {
    id: "session.new",
    title: "New session",
    description: "Create a new interactive session.",
    category: "Session",
    slash: { name: "new" },
  },
  {
    id: "session.list",
    title: "Switch session",
    description: "Browse and switch replay sessions.",
    category: "Session",
    slash: { name: "sessions" },
    keybinding: { key: "g", ctrl: true, meta: false, shift: false },
    suggested: true,
  },
  {
    id: "session.inspect",
    title: "Inspect session",
    description: "Replay-first inspect report for the current session.",
    category: "Session",
    slash: { name: "inspect" },
    keybinding: { key: "i", ctrl: true, meta: false, shift: false },
  },
  {
    id: "session.context",
    title: "Context",
    description: "Open the read-only context pressure and compaction dashboard.",
    category: "Session",
    slash: { name: "context", argumentMode: "optional" },
    suggested: true,
  },
  {
    id: "session.transcript",
    title: "Transcript snapshot",
    description: "Open a read-only transcript snapshot in the external pager.",
    category: "Session",
    slash: { name: "transcript" },
  },
  {
    id: "session.diff",
    title: "Diff",
    description: "Open the working-tree and session diff view.",
    category: "Session",
    slash: { name: "diff" },
  },
  {
    id: "transcript.copy",
    title: "Copy latest answer",
    description: "Copy the latest assistant response as Markdown.",
    category: "Transcript",
    slash: { name: "copy" },
  },
  {
    id: "session.export",
    title: "Export session",
    description: "Export a replay-visible session handoff bundle.",
    category: "Session",
    slash: { name: "export" },
  },
  {
    id: "session.lineage",
    title: "Lineage tree",
    description: "Browse and checkout session lineage branches.",
    category: "Session",
    slash: { name: "lineage" },
    suggested: true,
  },
  {
    id: "session.queue",
    title: "Queued prompts",
    description: "Inspect and delete queued prompts for the current session.",
    category: "Session",
    discovery: { help: false },
    keybinding: { key: "b", ctrl: true, meta: false, shift: false },
    suggested: true,
  },
  {
    id: "session.undo",
    title: "Undo last turn",
    description: "Undo the last submitted turn and restore its prompt.",
    category: "Session",
    slash: { name: "undo" },
  },
  {
    id: "session.redo",
    title: "Redo last turn",
    description: "Redo the last undone turn.",
    category: "Session",
    slash: { name: "redo" },
  },
  {
    id: "session.rewind",
    title: "Rewind to checkpoint",
    description: "Pick an earlier checkpoint on the active branch and fork from it.",
    category: "Session",
    slash: { name: "rewind", argumentMode: "optional" },
  },
  {
    id: "agent.model",
    title: "Switch model",
    description: "Select a model for the current session.",
    category: "Agent",
    slash: { name: "model", argumentMode: "optional" },
    suggested: true,
  },
  {
    id: "agent.preset.next",
    title: "Next model preset",
    description: "Cycle the model preset for the current session.",
    category: "Agent",
    keybinding: { key: "tab", ctrl: false, meta: false, shift: true },
    discovery: { help: false },
  },
  {
    id: "agent.connect",
    title: "Connect provider",
    description: "Connect a model provider.",
    category: "Agent",
    discovery: { help: false },
  },
  {
    id: "agent.think",
    title: "Select thinking level",
    description: "Select the model thinking level for future turns.",
    category: "Agent",
    discovery: { help: false },
  },
  {
    id: "agent.steer",
    title: "Steer current turn",
    description: "Append an in-flight hint to the current tool-result boundary.",
    category: "Agent",
    slash: { name: "steer", argumentMode: "required" },
  },
  {
    id: "view.thinking",
    title: "Toggle thinking blocks",
    description: "Show or hide reasoning blocks in the transcript.",
    category: "View",
    discovery: { help: false },
  },
  {
    id: "view.toolDetails",
    title: "Toggle tool details",
    description: "Show or hide completed tool details in the transcript.",
    category: "View",
    discovery: { help: false },
  },
  {
    id: "view.diffWrap",
    title: "Toggle diff wrapping",
    description: "Toggle wrapping in diff views.",
    category: "View",
    discovery: { help: false },
  },
  {
    id: "view.diffStyle",
    title: "Toggle diff style",
    description: "Toggle automatic split diffs and stacked unified diffs.",
    category: "View",
    discovery: { help: false },
  },
  {
    id: "operator.approvals",
    title: "Approvals",
    description: "Review queued approval requests.",
    category: "Operator",
    slash: { name: "approvals" },
    keybinding: { key: "a", ctrl: true, meta: false, shift: false },
  },
  {
    id: "runtime.authority",
    title: "Authority",
    description: "Open the read-only runtime authority posture view.",
    category: "Operator",
    slash: { name: "authority" },
    suggested: true,
  },
  {
    id: "operator.inbox",
    title: "Inbox",
    description: "Open pending operator questions and shell notifications.",
    category: "Operator",
    slash: { name: "inbox" },
    keybinding: { key: "n", ctrl: true, meta: false, shift: false },
    suggested: true,
  },
  {
    id: "operator.questions",
    title: "Operator questions",
    description: "Open pending operator questions only.",
    category: "Operator",
    discovery: { help: false },
    keybinding: { key: "o", ctrl: true, meta: false, shift: false },
  },
  {
    id: "operator.tasks",
    title: "Tasks",
    description: "Inspect background task runs.",
    category: "Operator",
    slash: { name: "tasks" },
    keybinding: { key: "t", ctrl: true, meta: false, shift: false },
  },
  {
    id: "operator.notifications",
    title: "Notifications",
    description: "Open shell notifications only.",
    category: "Operator",
    discovery: { help: false },
  },
  {
    id: "operator.answer",
    title: "Answer operator question",
    description: "Answer a pending operator prompt.",
    category: "Operator",
    slash: { name: "answer", argumentMode: "required" },
  },
  {
    id: "system.theme",
    title: "Switch theme",
    description: "List or switch interactive shell themes.",
    category: "System",
    slash: { name: "theme", argumentMode: "optional" },
  },
  {
    id: "skills.catalog",
    title: "Skills",
    description: "Open the skill and producer catalog.",
    category: "Skills",
    slash: { name: "skills" },
    suggested: true,
  },
  {
    id: "project.init",
    title: "Initialize project guidance",
    description: "Preview Brewva project guidance initialization.",
    category: "Project",
    slash: { name: "init" },
  },
  {
    id: "context.requestCompaction",
    title: "Context: request compaction",
    description: "Submit a durable context compaction request for the current session.",
    category: "Context",
  },
  {
    id: "transcript.copyLatestAnswer",
    title: "Transcript: copy latest answer",
    description: "Copy the latest assistant response as Markdown.",
    category: "Transcript",
  },
  {
    id: "session.exportInspectBundle",
    title: "Session: export inspect bundle",
    description: "Open a replay-first inspect bundle for export.",
    category: "Session",
  },
  {
    id: "diff.exportPatchEvidence",
    title: "Diff: export patch evidence",
    description: "Open working-tree diff evidence for export.",
    category: "Diff",
  },
  {
    id: "composer.stash",
    title: "Stash prompt",
    description: "Browse stashed prompt drafts.",
    category: "Composer",
    discovery: { help: false },
    keybinding: { key: "s", ctrl: true, meta: false, shift: false },
  },
  {
    id: "composer.unstash",
    title: "Restore latest stash",
    description: "Restore the latest stashed prompt.",
    category: "Composer",
    discovery: { help: false },
    keybinding: { key: "y", ctrl: true, meta: false, shift: false },
  },
];

const reservedShellSlashNames: readonly ShellSlashReservation[] = [
  {
    name: "questions",
    owner: "runtime.questions",
    message:
      "Use /inbox in the interactive shell; /questions remains a headless extension command.",
  },
  {
    name: "insights",
    owner: "runtime.insights",
    message:
      "/insights is reserved for runtime and channel operator flows; it is not an interactive shell slash command.",
  },
  {
    name: "update",
    owner: "runtime.update",
    message:
      "/update is reserved for runtime and channel control workflows; it is not an interactive shell slash command.",
  },
  {
    name: "agent-overlays",
    owner: "runtime.agent-overlays",
    message:
      "/agent-overlays is reserved for custom subagent inspection; it is not an interactive shell slash command.",
  },
  {
    name: "compact",
    owner: "runtime.context",
    message: "Use /context, then Request compaction; /compact is not a Brewva command.",
    redirectCommandId: "session.context",
  },
  {
    name: "permissions",
    owner: "runtime.authority",
    message: "Use /authority for posture and /approvals for pending commitments.",
    redirectCommandId: "runtime.authority",
  },
  {
    name: "review",
    owner: "runtime.skills",
    message: "Use /skills to discover review workflows.",
    redirectCommandId: "skills.catalog",
  },
  {
    name: "security-review",
    owner: "runtime.skills",
    message: "Use /skills to discover security review workflows.",
    redirectCommandId: "skills.catalog",
  },
];

export function registerShellCommands(commandProvider: ShellCommandProvider): void {
  for (const command of builtInShellCommands) {
    commandProvider.register(command);
  }
  commandProvider.reserveSlashNames(reservedShellSlashNames);
}
