export {
  applySourceEdits,
  clearParsedSourceCache,
  collectSymbols,
  detectLanguage,
  diffIntroducedFatalParseErrors,
  extractLineSnippet,
  findIdentifierAtPosition,
  findOccurrences,
  formatOccurrenceLine,
  formatSymbolLine,
  isParsableFile,
  isValidIdentifierName,
  lineColumnToOffset,
  offsetToLineColumn,
  parseSource,
  renameInFile,
  walkAst,
  type AstNode,
  type AstWalker,
  type CollectSymbolsOptions,
  type FindOccurrencesMode,
  type FindOccurrencesOptions,
  type IdentifierAtPosition,
  type IdentifierKind,
  type IdentifierOccurrence,
  type OxcError,
  type ParsedSource,
  type ParseLanguage,
  type RenameResult,
  type SourceEdit,
  type SourceSymbol,
  type SourceSymbolKind,
} from "./oxc-source.js";
