import {
  DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_CONSUMED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_DECIDED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_REQUESTED_EVENT_TYPE,
  PATCH_RECORDED_EVENT_TYPE,
  REASONING_CHECKPOINT_EVENT_TYPE,
  REASONING_REVERT_EVENT_TYPE,
  RECOVERY_WAL_APPENDED_EVENT_TYPE,
  REVERSIBLE_MUTATION_PREPARED_EVENT_TYPE,
  REVERSIBLE_MUTATION_RECORDED_EVENT_TYPE,
  REVERSIBLE_MUTATION_ROLLED_BACK_EVENT_TYPE,
  ROLLBACK_EVENT_TYPE,
  SCHEDULE_EVENT_TYPE,
  SESSION_COMPACT_EVENT_TYPE,
  TASK_EVENT_TYPE,
  TOOL_RESULT_RECORDED_EVENT_TYPE,
  TRUTH_EVENT_TYPE,
  TURN_INPUT_RECORDED_EVENT_TYPE,
  TURN_RENDER_COMMITTED_EVENT_TYPE,
  VERIFICATION_OUTCOME_RECORDED_EVENT_TYPE,
  type BrewvaEventRecord,
} from "@brewva/brewva-runtime/events";

export const SESSION_INDEX_TEXT_INDEXED_EVENT_TYPES = [
  TASK_EVENT_TYPE,
  TRUTH_EVENT_TYPE,
  TOOL_RESULT_RECORDED_EVENT_TYPE,
  SESSION_COMPACT_EVENT_TYPE,
  TURN_INPUT_RECORDED_EVENT_TYPE,
  TURN_RENDER_COMMITTED_EVENT_TYPE,
  REASONING_CHECKPOINT_EVENT_TYPE,
  REASONING_REVERT_EVENT_TYPE,
  SCHEDULE_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_REQUESTED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_DECIDED_EVENT_TYPE,
  EFFECT_COMMITMENT_APPROVAL_CONSUMED_EVENT_TYPE,
  REVERSIBLE_MUTATION_PREPARED_EVENT_TYPE,
  REVERSIBLE_MUTATION_RECORDED_EVENT_TYPE,
  REVERSIBLE_MUTATION_ROLLED_BACK_EVENT_TYPE,
  RECOVERY_WAL_APPENDED_EVENT_TYPE,
  ROLLBACK_EVENT_TYPE,
  PATCH_RECORDED_EVENT_TYPE,
  DECISION_RECEIPT_RECORDED_EVENT_TYPE,
  VERIFICATION_OUTCOME_RECORDED_EVENT_TYPE,
] as const;

const SESSION_INDEX_TEXT_INDEXED_EVENT_TYPE_SET: ReadonlySet<string> = new Set(
  SESSION_INDEX_TEXT_INDEXED_EVENT_TYPES,
);

export function isSessionIndexTextIndexedEventType(type: string): boolean {
  return SESSION_INDEX_TEXT_INDEXED_EVENT_TYPE_SET.has(type);
}

export function isSessionIndexTextIndexedEvent(event: Pick<BrewvaEventRecord, "type">): boolean {
  return isSessionIndexTextIndexedEventType(event.type);
}
