import type { BrewvaEventRecord } from "@brewva/brewva-vocabulary/events";
import {
  APPROVAL_DECIDED_EVENT_TYPE,
  APPROVAL_REQUESTED_EVENT_TYPE,
  CLAIM_UPSERTED_EVENT_TYPE,
  REASONING_CHECKPOINT_EVENT_TYPE,
  REASONING_REVERT_EVENT_TYPE,
  TOOL_RESULT_RECORDED_EVENT_TYPE,
  VERIFICATION_OUTCOME_RECORDED_EVENT_TYPE,
} from "@brewva/brewva-vocabulary/iteration";
import { SCHEDULE_EVENT_TYPE } from "@brewva/brewva-vocabulary/schedule";
import {
  RECOVERY_WAL_APPENDED_EVENT_TYPE,
  SESSION_COMPACT_EVENT_TYPE,
  SESSION_TITLE_GENERATED_EVENT_TYPE,
  TURN_INPUT_RECORDED_EVENT_TYPE,
  TURN_RENDER_COMMITTED_EVENT_TYPE,
} from "@brewva/brewva-vocabulary/session";
import { TASK_SPEC_SET_EVENT_TYPE } from "@brewva/brewva-vocabulary/task";
import { USER_FACT_RECORDED_EVENT_TYPE } from "@brewva/brewva-vocabulary/user-model";
import {
  ROLLBACK_EVENT_TYPE,
  SOURCE_PATCH_APPLIED_EVENT_TYPE,
} from "@brewva/brewva-vocabulary/workbench";

export const SESSION_INDEX_TEXT_INDEXED_EVENT_TYPES = [
  TASK_SPEC_SET_EVENT_TYPE,
  CLAIM_UPSERTED_EVENT_TYPE,
  TOOL_RESULT_RECORDED_EVENT_TYPE,
  SESSION_COMPACT_EVENT_TYPE,
  SESSION_TITLE_GENERATED_EVENT_TYPE,
  TURN_INPUT_RECORDED_EVENT_TYPE,
  TURN_RENDER_COMMITTED_EVENT_TYPE,
  REASONING_CHECKPOINT_EVENT_TYPE,
  REASONING_REVERT_EVENT_TYPE,
  SCHEDULE_EVENT_TYPE,
  APPROVAL_REQUESTED_EVENT_TYPE,
  APPROVAL_DECIDED_EVENT_TYPE,
  RECOVERY_WAL_APPENDED_EVENT_TYPE,
  ROLLBACK_EVENT_TYPE,
  SOURCE_PATCH_APPLIED_EVENT_TYPE,
  VERIFICATION_OUTCOME_RECORDED_EVENT_TYPE,
  USER_FACT_RECORDED_EVENT_TYPE,
] as const;

const SESSION_INDEX_TEXT_INDEXED_EVENT_TYPE_SET: ReadonlySet<string> = new Set(
  SESSION_INDEX_TEXT_INDEXED_EVENT_TYPES,
);

export function isSessionIndexTextIndexedEventType(type: string): boolean {
  return SESSION_INDEX_TEXT_INDEXED_EVENT_TYPE_SET.has(type);
}

export function isSessionIndexTextIndexedEvent(event: Pick<BrewvaEventRecord, "type">): boolean {
  return isSessionIndexTextIndexedEventType(event.type);
}
